runtime: php55
api_version: 1

env_variables:

  MYSQL_DSN: mysql:unix_socket=/cloudsql/chalpartyco:asia-northeast1:partydb;dbname=party
  MYSQL_USER: root
  MYSQL_PASSWORD: indialovesfootball
  MYSQL_DATABASE: party
  MYSQL_SOCKET: /cloudsql/chalpartyco:asia-northeast1:partydb

handlers:
- url: /
  script: www/index.php
  secure: always
  redirect_http_response_code: 301

- url: /index.php
  script: www/index.php
  secure: always
  redirect_http_response_code: 301

- url: /party.php
  script: www/party.php
  secure: always
  redirect_http_response_code: 301

- url: /place.php
  script: www/place.php
  secure: always
  redirect_http_response_code: 301

- url: /style.css
  static_files: www/style.css
  upload: www/style.css
  secure: always
  redirect_http_response_code: 301

- url: /robots.txt
  static_files: www/robots.txt
  upload: www/robots.txt
  secure: always
  redirect_http_response_code: 301

- url: /image
  static_dir: www/image
  secure: always
  redirect_http_response_code: 301

- url: /sitemap.xml
  static_files: www/sitemap.xml
  upload: www/sitemap.xml
  secure: always
  redirect_http_response_code: 301

- url: /favicon.ico
  static_files: www/favicon.ico
  upload: www/favicon.ico
  secure: always
  redirect_http_response_code: 301

- url: /.*
  script: www/handler.php
  secure: always
  redirect_http_response_code: 301

